Update path.init

diff --git a/init/path.init b/init/path.init
--- a/init/path.init
+++ b/init/path.init
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-export PATH LD_LIBRARY_PATH PKG_CONFIG_PATH PYTHONPATH MANPATH CMAKE_SYSTEM_PREFIX_PATH
+export PATH LD_LIBRARY_PATH PKG_CONFIG_PATH PYTHONPATH MANPATH CMAKE_SYSTEM_PREFIX_PATH PYTHONHOMESITE
 
 add_path() {
     #echo "Checking $1=${!1}"
@@ -15,50 +15,98 @@ add_path() {
     fi
 }
 
-add_path_env() {
+remove_path() {
+    $DEBUG && echo "Removing ""$2"" from $1"
+    local v=":${!1}:"
+    local s=":$2:"
+    v="${v//$s/:}"
+    v="${v#:}"
+    v="${v%:}"
+    export $1="$v"
+}
+
+std_path_env() {
     if [ -d "$1" ]; then
 
-        add_path CMAKE_SYSTEM_PREFIX_PATH "$1"
+        $2 CMAKE_PREFIX_PATH "$1"
 
 # binary directories
         if [ -d "$1/bin" ]; then
-            add_path PATH "$1/bin"
+            $2 PATH "$1/bin"
         fi
 
 # python directories
-        add_path PYTHONHOMESITE "${1}"
-        add_path PYTHONHOMESITE "${1}"
+        $2 PYTHONHOMESITE "${1}"
+        $2 PYTHONHOMESITE "${1}"
 
 # library directories
         for lib in "$1/lib" "$1/lib64"; do
             if [ -d "$lib" ]; then
-                add_path LD_LIBRARY_PATH "$lib"
-                add_path PKG_CONFIG_PATH "$lib/pkgconfig"
+                $2 LD_LIBRARY_PATH "$lib"
+                $2 PKG_CONFIG_PATH "$lib/pkgconfig"
             fi
         done
 
 # man directories
         if [ -d "$1/share/man" ]; then
-            add_path MANPATH "$1/share/man"
+            $2 MANPATH "$1/share/man"
         fi
-        add_path_env "$1/usr"
+        std_path_env "$1/usr" $2
     fi
+}
+
+add_path_env() {
+    std_path_env "$1" add_path
+}
+
+rem_path_env() {
+    std_path_env "$1" remove_path
 }
 
 for dir in /usr /opt ~ ~/.local ~/.local/$MACHTYPE ~/.local/$HOSTNAME; do
     add_path_env $dir
 done
+add_path PYTHONPATH ~/.python-site
 
-setup_path() {
+ensure_abs_path() {
+    local p="${1%/}"
+    if [[ "$p" != /* ]]; then
+        rp=$(type -p realpath)
+        if [ "x$rp" != "x" ]; then
+            $rp $p
+        else
+            echo "Can't find realpath, do not know how to find an absolute path from a relative path" >&2
+            return 1
+        fi
+    else
+        echo $p
+    fi
+}
+
+init_path() {
     if [ "x$1" != "x" ]; then
-        if [ "$1" != "/*" ]; then
-            echo "Setup path does not support relative paths."
+        p=$(ensure_abs_path $1)
+        if [ "x$p" == "x" ]; then
             return
         fi
-        echo "Setting paths for $1"
-        add_path_env "$1"
+        echo "Setting paths for $p"
+        add_path_env "$p"
     else
         echo "Setting paths for $(pwd)"
         add_path_env "$(pwd)"
+    fi
+}
+
+deinit_path() {
+    if [ "x$1" != "x" ]; then
+        p=$(ensure_abs_path $1)
+        if [ "x$p" == "x" ]; then
+            return
+        fi
+        echo "Unsetting paths for $p"
+        rem_path_env "$p"
+    else
+        echo "Unsetting paths for $(pwd)"
+        rem_path_env "$(pwd)"
     fi
 }
